language: java


git:
  depth: false  #Disabilitiamo lo shallow clone (cloniamo per gli ultimi N commit)
  autocrlf: input

os:
  - linux
  - osx
  - windows

install: true

# List di script
script:
  - ./gradlew check
